name: Deployment to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Build and deploy backend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "backend-flight-booking-app"
          heroku_email: "mail@silaspohl.de"
          appdir: "backend"
          usedocker: true
        env:
          HD_POSTGRES_DATABASE: ${{secrets.POSTGRES_DATABASE}}
          HD_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          HD_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          HD_POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          HD_POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
          HD_ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
          HD_REFRESH_TOKEN_SECRET: ${{secrets.REFRESH_TOKEN_SECRET}}
          HD_ALGORITHM: ${{secrets.ALGORITHM}}
          HD_ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
          HD_EMAIL_ADDRESS: ${{secrets.EMAIL_ADDRESS}}
          HD_EMAIL_PASSWORD: ${{secrets.EMAIL_PASSWORD}}

      - name: Build and deploy frontend
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "frontend-flight-booking-app"
          heroku_email: "mail@silaspohl.de"
          appdir: "frontend"
          usedocker: true
        env:
          HD_API_URL: "https://backend-flight-booking-app.herokuapp.com/"
